apiVersion: apps/v1
kind: Deployment

metadata:
  name: devops-node-app
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: devops-node-app

  template:
    metadata:
      labels:
        app: devops-node-app

    spec:
      containers:
        - name: devops-node-app

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}

          envFrom:
            - configMapRef:
                name: devops-node-config
            - secretRef:
                name: devops-node-secret

          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 15

          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10

          resources:
{{ toYaml .Values.resources | indent 12 }}