services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: devops-node-app

    ports:
      - "8000:8000"

    environment:
      PORT: 8000

    restart: unless-stopped
