namespace: "devops-demo"

replicaCount: 2

image:
  repository: 060763492167.dkr.ecr.us-east-1.amazonaws.com/devops-node-app
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: alb
  host: api.lenapp.click
  certificateArn: arn:aws:acm:us-east-1:060763492167:certificate/fe632eb6-5f43-48ca-bfbf-1af9d4fe2acb

config:
  PORT: "8000"

secret:
  APP_ENV: production

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpu: 70
